### ISSUE TITLE
Sharing Bib(La)TeX test cases?

### ISSUE THREAD

**Issue by zuphilip** [citation-js/bibtex-parser-experiments#1]
Do you want to share the Bib(La)TeX test cases as well? Or are they already somewhere online available, but I couldn't find them?

I wanted to analyze Zotero's behavior on them and use them for possible improvements of its BibTeX import translator (e.g. supporting `electronic` as it seems to be an alias for `online`).

**Comment by larsgw** [comment]
They're not online yet (apart from the syntax one, which is in [my blog post](https://larsgw.blogspot.com/2019/10/bibtex-rework-syntax-update.html)). The large test case is an export from someone's CiteULike, which I'm not at liberty to share at the moment, but I'll ask again.

I'll try to make a test suite as well.

**Comment by larsgw** [comment]
Also, I don't know if I can publish them under an open license, given all the `abstract`s, and removing those would really impact the tests, I think.

**Comment by zuphilip** [comment]
Okay, I understand. Yeah, I am already examining the example you provided in your blog post. Well, I am looking for a handful more hard test cases possibly with `preamble` and `string`s as well as of the type `electronic` (the abstract is for me not in the focus). Maybe, this is possible to provide?

**Comment by zuphilip** [comment]
I fixed some issues from your example given in the PR https://github.com/zotero/translators/pull/2020 . However, I haven't looked into [concatenating strings](http://www.bibtex.org/Format/) or the very unusual writing of the `@preamble` in this example.

**Comment by larsgw** [comment]
The test cases are in https://github.com/citation-js/bibtex-parser-experiments/tree/master/test/files now. In my opinion, the unusual `@preamble` has no use and should have no usage (although `biblatex` does seem to support it).

**Comment by zuphilip** [comment]
Thank you very much! :bowing_man: 

The concatenation is added in the PR now and I guess I will ignore the unusual preamble as it will not change the output.
