### ISSUE TITLE
Zotero parser comparison

### ISSUE THREAD

**Issue by retorquere** [citation-js/bibtex-parser-experiments#12]
The Zotero parser isn't really compared in the same way as the others -- it starts a full-blown translation server which does a lot more. The Zotero translators aren't really meant to be ran standalone but I've created a haphazard test runner for the bibtex translator [here](https://gist.github.com/retorquere/110ba7ce9ee252c309c974672913fcca), and that runs on `long.bib` in 7s.

**Comment by larsgw** [comment]
I'm still only getting to 15s but that may just be hardware I suppose.
