### ISSUE TITLE
What should I run so I can run the tests?

### ISSUE THREAD

**Issue by retorquere** [citation-js/bibtex-parser-experiments#5]
I've ran

```
npm run babel
npm run nearley
npm run astrocite
npm test
```

but I still get

```
Error: Cannot find module './grammar'
```

**Comment by larsgw** [comment]
Can you run `tree` or something similar on the `src` directory so I can compare?

**Comment by larsgw** [comment]
Actually, I think it's just that `npm run babel` should be done last as it has to copy the generated `grammar.js` files.

**Comment by retorquere** [comment]
```
npm run babel && npm test
```

seems to do the job (at least I see no error, still waiting for output)

might be convenient to add

```
"pretest": "npm run babel"
```

to package.json

**Comment by larsgw** [comment]
Yeah, I noticed I forgot to as well. Usually I have `@babel/register` for tests.
